sonar.projectKey=shuvo2115015-blip_ecogrid-quality-analysis
sonar.organization=shuvo2115015-blip
sonar.projectName=EcoGrid Quality Analysis
sonar.projectVersion=1.0

sonar.sources=.
sonar.inclusions=ecogrid.py
sonar.tests=.
sonar.test.inclusions=test_ecogrid.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
